Add release_date sort
streamchaser/streamchaser pull request #261
Opened 2022-07-16 08:00 UTC by AndreasPB

# Description

* Adds the ability to sort by release date
* Adds tests for release_date and popularity

Part of #248 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2022-07-16 13:16 UTC, Primdahl26 requested changes
Dont we need to add this to our `Meilisearch` endpoint? How would we query it through the API otherwise?

2022-07-16 17:47 UTC, AndreasPB commented
> Dont we need to add this to our `Meilisearch` endpoint? How would we query it through the API otherwise?

Derp, that went a little too fast :D 

I went all out with Swagger documentation and enums. I also pulled popularity out as an option, so we are back to the "real" MeiliSearch way with the ranking rules we have set up.

Side note for the frontend: You wont get much out of having to sorts on at the same time, so that should probably be prevented

2022-07-20 21:44 UTC, AndreasPB commented on frontend/src/components/filters.svelte
> +
Can we make it not use the popularity sorting when the user has input(unless it was actively selected)

2022-07-20 22:37 UTC, AndreasPB commented on frontend/src/routes/index.svelte
> +    }
Can we have a third option(byDefault(?)) that does this with the !input and have the old behavior on byPopularity and byReleaseDate?

2022-11-11 14:01 UTC, Pankai222 commented
<img src="https://media0.giphy.com/media/aGSjh8J7Nb2yGgm1C4/giphy.gif"/>

2022-11-11 14:07 UTC, nullxDEADBEEF approved these changes
SGUFM :shipit: <img src="https://media1.giphy.com/media/3o7WIPku0tmvhunqwg/giphy.gif"/>

2022-11-11 14:07 UTC, Primdahl26 approved these changes

2022-11-11 14:08 UTC, merged